name: Deploy Production

on:
  workflow_run:
    workflows: [Deploy UAT]
    types: [completed]

jobs:
  deploy:
    environment: Production
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: true
